name: Upload Release Files to AWS S3

on:
  push:
  release:
    types: 
      - created
      - published

jobs:
  upload-release:
    name: "Upload Release Files to AWS S3"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest release of ONLYOFFICE documents apk
        uses: rez0n/actions-github-release@main
        id: documents-apk
        with:
          token: ${{ secrets.TOKEN }}
          repository: "onlyoffice/documents-app-android"
          type: "latest"

      - name: Check directory
        run: echo ${{ steps.documents-apk.outputs.release }}

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
