name: Upload Release Files to AWS S3

on:
  push:
  release:
    types: 
      - created
      - published

jobs:
  upload-release:
    name: "Upload Release Files to AWS S3"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload asset to github release page
        uses: paweb88/fetch-gh-release-asset-composite@main
        with:
          repo: "onlyoffice/documents-app-android"
          version: "tags/v8.1.0-534"
          file: "onlyoffice-manager-8.0.1-533.apk"
          target: "./onlyoffice-manager-8.0.1-533.apk"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
