name: Upload Release Files to AWS S3

on:
  push:
  release:
    types: 
      - created
      - published

jobs:
  upload-release:
    name: "Upload Release Files to AWS S3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download APK file and Upload on AWS S3
        run: |
          GITHUB_TOKEN=${{ secrets.TOKEN }}
          GITHUB_API_URL=https://api.github.com/repos/ONLYOFFICE/documents-app-android/releases/latest

          release_info=$(curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" -s $GITHUB_API_URL)
          release_tag=$(echo "$release_info" | jq -r '.tag_name')
          release_id=$(echo "$release_info" | jq -r '.id')

          apk_url=$(echo "$release_info" | jq -r '.assets[] | select(.name | test("onlyoffice-manager-.*\\.apk")) | .browser_download_url')

          if [ ! -z "$apk_url" ]; then
              curl -o onlyoffice-documents.apk -L "$apk_url"
          else
              echo "Error: APK file not found in the release assets."
              exit 1
          fi
          ls -lha
          

      - name: Invalidate AWS CLOUDFRONT cache
        run: |
             aws cloudfront create-invalidation \
                --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} \
                --paths \
                "/install/mobile/android/onlyoffice-documents.apk"          

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
