name: Upload Release Files to AWS S3

on:
  push:
  release:
    types: 
      - created
      - published

jobs:
  upload-release:
    name: "Upload Release Files to AWS S3"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v1
        with:
          github_token: ${{ secrets.TOKEN }}

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
